# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.clean:
        class: AppBundle\Utils\Clean
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments:
            assets: "@assets.packages"
        tags:
            - { name: twig.extension }
    app.virtualiseHelper:
        class: AppBundle\Utils\virtualiseHelper
        calls:
         - [setEntityManager, ["@doctrine.orm.entity_manager"]]
